name: GitHub Slack Workflow Notifications
description: Fully detailed GitHub Actions workflow notifications in Slack

branding:
  color: green
  icon: message-square

inputs:
  github-token:
    description: The GitHub token used to update the pull-request
    default: ${{ github.token }}

  slack-webhook:
    description: A Slack Webhook URL
    required: true

  ignore-jobs:
    description: Comma separated list of job names to ignore

  ignore-steps:
    description: Comma separated list of step names to ignore
    default:  Set up job, Complete job


runs:
  using: docker
  image: docker://ghcr.io/ahmadnassri/action-slack-workflow-notifications:v1
